config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls'), name='core')
]

core/urls.py
from importlib.machinery import ExtensionFileLoader
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path("", views.index_view, name='index'),
    path("aspetos/", views.aspetos_view, name='aspetos'),
    path("cenario/", views.cenario_view, name='cenario'),
    path("diagrama/", views.diagrama_view, name='diagrama'),
    path("planeamento/", views.planeamento_view, name='planeamento'),
    path("plan2/", views.plan2_view, name='plan2'),
    path("plan3/", views.plan3_view, name='plan3'),
    path("trafego/", views.trafego_view, name='trafego'),
    path("erlangB/", views.erlangB_view, name='erlangB'),
    path("canais/", views.canais_view, name='canais'),
    path("calctraf/", views.calctraf_view, name='calctraf'),
    path("topicos/", views.topicos_view, name='topicos'),
    path("Conversor/", views.conversor_view, name='conversor'),
    path("nyquist/", views.nyquist_view, name='nyquist'),
    path("shannon/", views.shannon_view, name='shannon'),
    path("meios/", views.meios_view, name='meios'),
    path("sinais/", views.sinais_view, name='sinais'),
    path("mpsk/", views.mpsk_view, name='mpsk'),
    path("mqam/", views.mqam_view, name='mqam'),
    path("modulacoes/", views.modulacoes_view, name='modulacoes'),
    path("edita_topicos", views.edita_topicos_view, name='edita_topicos'),
    path("novo_topico/", views.novo_topico_view, name='novo_topico'),
    path("edita_topico/<int:topico_id>", views.edita_topico_view, name='edita_topico'),
    path("apaga_topico/<int:topico_id>", views.apaga_topico_view, name='apaga_topico'),
    path("novo_conteudo/", views.novo_conteudo_view, name='novo_conteudo'),
    path("edita_conteudo/<int:conteudo_id>", views.edita_conteudo_view, name='edita_conteudo'),
    path("apaga_conteudo/<int:conteudo_id>", views.apaga_conteudo_view, name='apaga_conteudo'),
]

core/models.py
from django.db import models

# Create your models here.
class Topico(models.Model):
    nome = models.CharField(max_length=50)
    ordem = models.IntegerField()

    def __str__(self):
        return f'{self.ordem}. {self.nome}'

class Conteudo(models.Model):
    descricao = models.CharField(max_length=200)
    ordem = models.IntegerField()
    topico = models.ForeignKey(Topico, related_name='conteudos', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.descricao}'

class Conversor(models.Model):
    tipo = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.tipo}'

class Nyquist(models.Model):
    tipo = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.tipo}'

class Shannon(models.Model):
    tipo = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.tipo}'

class Meios(models.Model):
    tipo = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.tipo}'

class mqam(models.Model):
    tipo = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.tipo}'     
    
class Aspetos(models.Model):
    tipo = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.tipo}'  
    
class Diagrama(models.Model):
    tipo = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.tipo}' 
    
class Planeamento(models.Model):
    tipo = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.tipo}'  

core/forms.py
from django.forms import ModelForm
from .models import Topico, Conteudo, Conversor, Nyquist, Shannon, Meios, Aspetos, Planeamento, Diagrama


class TopicoForm(ModelForm):
    class Meta:
        model = Topico
        fields = '__all__'

class ConteudoForm(ModelForm):
    class Meta:
        model = Conteudo
        fields = '__all__'

class ConversorForm(ModelForm):
    class Meta:
        model = Conversor
        fields = '__all__' 

class NyquistForm(ModelForm):
    class Meta:
        model = Nyquist
        fields = '__all__'    

class ShannonForm(ModelForm):
    class Meta:
        model = Shannon
        fields = '__all__'   

class MeiosForm(ModelForm):
    class Meta:
        model = Meios
        fields = '__all__' 

class AspetosForm(ModelForm):
    class Meta:
        model = Aspetos
        fields = '__all__' 

class PlaneamentoForm(ModelForm):
    class Meta:
        model = Aspetos
        fields = '__all__' 

core/views.py
from django.shortcuts import redirect, render
from .models import Topico, Conteudo, Conversor
from .forms import TopicoForm, ConteudoForm, ConversorForm
import seaborn as sns
import os
from .funcoes import calculateNyquist, calculateShannon, conversor, erlang_b_numero_canais, erlang_b_tráfego, plot_heatmap_ci, plot_relacao_ci, plot_variacao_atenuacao, plot_variacao_atenuacao_freq, qam, cria_matriz, calcula_matriz_prx, calcula_matriz_espaco_livre, grafico, dadosPlo, espaco_livre, calcular_heatmap_potencia, erlang_b_probabilidade_bloqueio

# Create your views here.
def index_view(request):
    return render(request, 'core/index.html')

def aspetos_view(request):
    return render(request, 'core/aspetos.html')

def topicos_view(request):

    topicos = Topico.objects.all().order_by('ordem')

    context = {
        'topicos':topicos
    }

    return render(request, 'core/topicos.html', context)

def conversor_view(request):
    resultado = "Resultado"
    if request.method == "POST":
        valor = request.POST['valor']
        unidade1 = request.POST['unidade1']
        unidade2 = request.POST['unidade2']
        resultado = conversor(valor, unidade1, unidade2)
    context = {
        'resultado': resultado
    }

    return render(request, 'core/conversor.html', context)

def nyquist_view(request):
    resultado = "Resultado"
    if request.method == "POST":
        b = request.POST['b']
        v = request.POST['v']
        resultado = calculateNyquist(b, v)
    context = {
        'resultado': resultado
    }

    return render(request, 'core/nyquist.html', context)

def shannon_view(request):
    resultado = "Resultado"
    if request.method == "POST":
        b = request.POST['b']
        snr = request.POST['snr']
        resultado = calculateShannon(b, snr)
    context = {
        'resultado': resultado
    }

    return render(request, 'core/shannon.html', context)

def meios_view(request):
    return render(request, 'core/meios.html')

def sinais_view(request):
    return render(request, 'core/sinais.html')

def mpsk_view(request):
    return render(request, 'core/mpsk.html')

def mqam_view(request):
    resultado = "Resultado"
    if request.method == "POST":
        b = request.POST['b']
        db = request.POST['db']
        ber = request.POST['ber']
        resultado = qam(b, db, ber)
    context = {
        'resultado': resultado
    }
    return render(request, 'core/mqam.html', context)

def modulacoes_view(request):
    return render(request, 'core/modulacoes.html')

def aspetos_view(request):
    if os.path.exists('static/core/grafico1.png'):
        os.remove('static/core/grafico1.png')
    if os.path.exists('static/core/grafico2.png'):
        os.remove('static/core/grafico2.png')   
    x_area = 100
    y_area = 100
    d_pixel = 1
    i_centro = 50
    j_centro = 50
    resultado = "Resultado"
    resultado1 = "Resultado1"
    matriz = cria_matriz(x_area, y_area, d_pixel)
    if request.method == "POST":
        ptx= request.POST['ptx']
        f = request.POST['f']
        d = request.POST['d']
        s = request.POST['s']
        prx = calcula_matriz_espaco_livre(d,f,ptx)
        matriz_ptx = calcula_matriz_prx(matriz, prx, f, calcula_matriz_espaco_livre, i_centro, j_centro, d_pixel)
        resultado = grafico(matriz_ptx)
        resultado1 = espaco_livre(ptx, f, d, s)
    context = {
        'resultado': resultado,
        'resultado1': resultado1
    }
    return render(request, 'core/aspetos.html', context)

def cenario_view(request):
    resultado = dadosPlo()
    context = {
        'resultado': resultado
    }
    return render(request, 'core/cenario.html', context)

def diagrama_view(request):
    if os.path.exists('static/core/grafico3.png'):
        os.remove('static/core/grafico3.png')
    resultado = "Resultado"
    if request.method == "POST":
        ptx= request.POST['ptx']
        f = request.POST['f']
        mod = request.POST['mod']
        largura = request.POST['largura']
        altura = request.POST['altura']
        resultado = calcular_heatmap_potencia(ptx, f, mod, largura, altura, tamanho_pixel=10,
                              antena='Omni', azimute_antena=0, altura_antena=20, altura_terminal=1.5)
    context = {
        'resultado': resultado
    }
    return render(request, 'core/diagrama.html', context)

def planeamento_view(request):
    if os.path.exists('static/core/grafico5.png'):
        os.remove('static/core/grafico5.png')
    resultado = "Resultado"
    if request.method == "POST":
        c = request.POST['c']
        f = request.POST['f']
        resultado = plot_variacao_atenuacao_freq(f,c)
    context = {
        'resultado': resultado
    }
    return render(request, 'core/planeamento.html', context)

def plan2_view(request):
    if os.path.exists('static/core/grafico8.png'):
        os.remove('static/core/grafico8.png')
    resultado = "Resultado"
    if request.method == "POST":
        f = request.POST['f']
        resultado = plot_variacao_atenuacao(f)
    context = {
        'resultado': resultado
    }
    return render(request, 'core/plan2.html', context)

def plan3_view(request):
    if os.path.exists('static/core/grafico7.png'):
        os.remove('static/core/grafico7.png')
    resultados1 = plot_relacao_ci()  
    resultado = plot_heatmap_ci()
    context = {
        'resultado': resultado,
        'resultados1': resultados1
    }
    return render(request, 'core/plan3.html', context)

def trafego_view(request):
    return render(request, 'core/trafego.html')

def erlangB_view(request):
    resultado = "Resultado"
    if request.method == "POST":
        t= request.POST['t']
        c = request.POST['c']
        resultado = erlang_b_probabilidade_bloqueio(t, c)
    context = {
        'resultado': resultado,
    }
    return render(request, 'core/erlangB.html', context)

def canais_view(request):
    resultado = "Resultado"
    if request.method == "POST":
        t= request.POST['t']
        pb = request.POST['pb']
        resultado = erlang_b_numero_canais(t, pb)
    context = {
        'resultado': resultado,
    }
    return render(request, 'core/canais.html', context)

def calctraf_view(request):
    resultado = "Resultado"
    if request.method == "POST":
        tc= request.POST['tc']
        dm = request.POST['dm']
        resultado = erlang_b_tráfego(tc, dm)
    context = {
        'resultado': resultado,
    }
    return render(request, 'core/calctraf.html', context)

def edita_topicos_view(request):

    topicos = Topico.objects.all().order_by('ordem')

    context = {
        'topicos':topicos
    }

    return render(request, 'core/edita_topicos.html', context)


def novo_topico_view(request):

    topico_form = TopicoForm(request.POST or None)
    if topico_form.is_valid():
        topico_form.save()
        return redirect('core:edita_topicos')

    context = {'topico_form':topico_form}
    return render(request, 'core/novo_topico.html', context)


def edita_topico_view(request, topico_id):

    topico = Topico.objects.get(id=topico_id)
    topico_form = TopicoForm(request.POST or None, instance=topico)
    if request.method == "POST" and topico_form.is_valid():
        topico_form.save()
        return redirect('core:edita_topicos')

    context = {'topico_form':topico_form, 'topico_id':topico_id}
    return render(request, 'core/edita_topico.html', context)


def apaga_topico_view(request, topico_id):
    topico = Topico.objects.get(id=topico_id)
    topico.delete()
    return redirect('core:edita_topicos')


def novo_conteudo_view(request):

    conteudo_form = ConteudoForm(request.POST or None)
    if conteudo_form.is_valid():
        conteudo_form.save()
        return redirect('core:edita_topicos')

    context = {'conteudo_form':conteudo_form}
    return render(request, 'core/novo_conteudo.html', context)


def edita_conteudo_view(request, conteudo_id):

    conteudo = Conteudo.objects.get(id=conteudo_id)
    conteudo_form = ConteudoForm(request.POST or None, instance=conteudo)
    if request.method == "POST" and conteudo_form.is_valid():
        conteudo_form.save()
        return redirect('core:edita_topicos')

    context = {'conteudo_form':conteudo_form, 'conteudo_id':conteudo_id}
    return render(request, 'core/edita_conteudo.html', context)


def apaga_conteudo_view(request, conteudo_id):
    conteudo = Conteudo.objects.get(id=conteudo_id)
    conteudo.delete()
    return redirect('core:edita_topicos')



templates/core/canais.html
{% extends "layout.html" %}

{% block style %}
<style>
    h2 {
        text-align: left;
        color: white;
    }

    h1 {
        width: 100%;
        padding: 15px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
        color: #34495e;
    }

    .formula {
        width: 100%;
        padding: 10px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 25px;
        color: black;
    }

    .text {
        margin-top: 60px;
        margin-right: 10px;
        color: white;
    }

    p {
        font-size: 20px;
    }

    .form {
        width: 100%;
        padding: 15px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    button {
        font: 400 18px Roboto, sans-serif;
        background-color: #34495e;
        border-radius: 5px;
        padding: 5px 10px;
        margin: 5px 2px;
        border: none;
    }

    form input {
        width: 100%;
        height: 60px;
        padding: 0 24px;
        margin: 5px 2px;
        color: #333;
        border: 1px solid #dcdce6;
        border-radius: 8px;
    }

    .resultado {
        margin-top: 30px;
        margin-left: 100px;
        color: white;
    }

    .c {
        width: 100%;
        padding: 15px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 30px;
        margin-left: 10px;
    }

    .left {
        text-align: left;
        float: left;
        width: 55%;
    }

    .right {
        float: right;
        width: 44%;
    }
    label {
        color: #333;
    }

    .resultado{
        width: 75%;
        padding: 10px;
        border-radius: 8px;
        margin-top: 25px;
        display: flex;
        justify-content: center;
        align-items: center;  
        color: white;
    }
    .formulario{
        margin-top: 100px;
    }

</style>
{% endblock style %}

{% block main %}
    <body>
        <div class="main">
            <div class="titulo">
                <div class="text">
                    <h1>Erlang B</h1>
                    <br>
                    <p>O Erlang B é um modelo matemático amplamente utilizado na teoria do tráfego para estimar a
                        probabilidade de bloqueio em um sistema de comunicação baseado em circuitos,
                        como um sistema telefônico. Ele fornece uma maneira de calcular a probabilidade de que as chamadas
                        sejam bloqueadas devido à falta de canais disponíveis no sistema.</p>
                    </p>
                    <div class="left">
                        <h2>Fórmula do Erlang B</h2>
                        <p>A fórmula do Erlang B para calcular a probabilidade de bloqueio, número de canais e tráfego é a
                            seguinte:</p>
                        <h3>Probabilidade de Bloqueio</h3>
                        <div class="formula">
                            <p>Probabilidade de Bloqueio = <sup>Tráfego<sup>Número de Canais</sup> / Número de Canais!</sup>
                                / Σ(k=0 até Número de Canais) <sup>Tráfego<sup>k</sup> / k!</sup></p>
                        </div>
                        <h3>Número de Canais</h3>
                        <div class="formula">
                            <p>Número de Canais = ln(Tráfego) - Σ(n=1 até Número de Canais) <sup>Tráfego<sup>n</sup></sup> /
                                n!</p>
                        </div>
                        <h3>Tráfego</h3>
                        <div class="formula">
                            <p>Tráfego = (Taxa de Chegada de Chamadas) * (Duração Média da Chamada)</p>
                        </div>
                    </div>
                    <div class="right">
                        <div class="formulario">
                           <h2>Cálculo do número de canais </h2>
                        <div class="c">
                            <form action="" method="POST">
                             {%csrf_token%}
                             <label>trafego: <input type="number" name="t"></label>
                             <br>
                             <label>probabilidade de bloqueio: <input type="number" name="pb"></label>
                             <br>
                             <button type="submit" style="color: white;">Calcular</button>
                         </form> 
                         </div> 
                         <div class="resultado">
                            <p>{{resultado}}</p>
                        </div> 
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </body>

{% endblock main %}

templates/core/cenario.html
{% extends "layout.html" %}

{% block style %}
<style>
    h1 {
        width: 100%;
        padding: 15px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
        color: #34495e;
    }
    .text {
        
        margin-top: 10px;
        margin-right: 10px;
        color: white;
    }
    p {
        font-size: 20px;
    }
    h2 {
        text-align: left;
        color: white;
    }
    img {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-left: 200px;
        margin-top: 20px;
    }
</style>
{% endblock style %}



{% block main %}
<body>
    <h1>Descriçaõ do cenário</h1>
    <div class="text">
        <h2>Cenário</h2>
        <p>Neste cenário, a campanha de medidas foi realizada em um escritório moderno de uma empresa de tecnologia. O escritório possui várias salas, corredores e uma área de descanso comum. A campanha de medidas teve como objetivo avaliar o decaimento do sinal WiFi com o aumento da distância em um ambiente corporativo.</p>
        <h2>Equipamento e Aplicações</h2>
        <p>Foram utilizados os seguintes equipamentos e aplicações:</p>
        <ol>
            <li>Dispositivos: Um telemóvel e um portátil.</li>
            <li>Aplicação: Wi-Fi Analyser, uma aplicação para PC que permite medir a intensidade do sinal WiFi recebido em dBm.</li>
        </ol>
        <h2>Configuração</h2>
        <p>A configuração utilizada para a transmissão do sinal WiFi foi a seguinte:</p>
        <ol>
            <li>Frequência de Operação: Definiu-se a frequência de operação em 2.4 GHz, que é uma frequência comum para redes WiFi.</li>
            <li>Potência Transmitida: A potência de transmissão do sinal WiFi foi ajustada para 15 dBm, que é um valor moderado.</li>
        </ol>
        <h2>Frequência Medida</h2>
        <p>Durante a campanha de medidas, a intensidade do sinal WiFi foi medida em uma frequência específica de 2.4 GHz. Essa frequência foi selecionada por ser amplamente utilizada em ambientes corporativos.</p>
        <h2>Fotografias</h2>
        <h2>Mapbox</h2>
        <div class="imagem">
            {% load static %}
            <img src= "{% static 'core/grafico4.png' %}" alt="">
        </div>
    </div>
    
</body>
{% endblock main %}

templates/core/edita_conteudo.html
{% extends "layout.html" %}

{% block style %}
<style>
    .caixa{
        width: 100%;
        padding: 15px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
    } 
    
    h3{
        color: white;
    }

</style>

{% endblock style %}

{% block main %}

    <h3>Edita Conteúdo</h3>

    <div>
        <form action=" {% url 'core:edita_conteudo' conteudo_id %}" method="POST">
            {% csrf_token %}

            <table>
                {{conteudo_form}}
            </table>
            <div class="botoes">
                <a href="{% url 'core:apaga_conteudo' conteudo_id %}" class="btn btn-outline-danger btn-sm">Apagar</a>    
                <input type="submit" value="Guardar" class="btn btn-primary btn-sm">
            </div>    
        </form>

    </div>


{% endblock main %}

</body>

</html>

templates/core/edita_topico.html
{% extends "layout.html" %}

{% block style %}
<style>
    .caixa{
        width: 100%;
        padding: 15px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
    } 
    h3{
        color: white;
    }

</style>

{% endblock style %}

{% block main %}

    <h3>Edita Tópico</h3>

    <div class="caixa">
        <form action="{% url 'core:edita_topico' topico_id %}" method="POST">
        {% csrf_token %}

        <table>
            {{topico_form}}
        </table>
    
        <input type="submit" class="btn btn-success  btn-sm" value="Guardar">
        <a href="{% url 'core:apaga_topico' topico_id %}" class="btn btn-outline-danger btn-sm">Apagar</a>
        </form>
    </div>



{% endblock main %}

</body>

</html>

templates/core/erlangB.html
{% extends "layout.html" %}

{% block style %}
<style>
    h2 {
        text-align: left;
        color: white;
    }

    h1 {
        width: 100%;
        padding: 15px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
        color: #34495e;
    }

    .formula {
        width: 100%;
        padding: 10px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 25px;
        color: black;
    }

    .text {
        margin-top: 60px;
        margin-right: 10px;
        color: white;
    }

    p {
        font-size: 20px;
    }

    .form {
        width: 100%;
        padding: 15px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    button {
        font: 400 18px Roboto, sans-serif;
        background-color: #34495e;
        border-radius: 5px;
        padding: 5px 10px;
        margin: 5px 2px;
        border: none;
    }

    form input {
        width: 100%;
        height: 60px;
        padding: 0 24px;
        margin: 5px 2px;
        color: #333;
        border: 1px solid #dcdce6;
        border-radius: 8px;
    }

    .resultado {
        margin-top: 30px;
        margin-left: 100px;
        color: white;
    }

    .c {
        width: 100%;
        padding: 15px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 30px;
        margin-left: 10px;
    }

    .left {
        text-align: left;
        float: left;
        width: 55%;
    }

    .right {
        float: right;
        width: 44%;
    }
    label {
        color: #333;
    }

    .resultado{
        width: 75%;
        padding: 10px;
        border-radius: 8px;
        margin-top: 25px;
        display: flex;
        justify-content: center;
        align-items: center;  
        color: white;
    }
    .formulario{
        margin-top: 100px;
    }

</style>
{% endblock style %}

{% block main %}
    <body>
        <div class="main">
            <div class="titulo">
                <div class="text">
                    <h1>Erlang B</h1>
                    <br>
                    <p>O Erlang B é um modelo matemático amplamente utilizado na teoria do tráfego para estimar a
                        probabilidade de bloqueio em um sistema de comunicação baseado em circuitos,
                        como um sistema telefônico. Ele fornece uma maneira de calcular a probabilidade de que as chamadas
                        sejam bloqueadas devido à falta de canais disponíveis no sistema.</p>
                    </p>
                    <div class="left">
                        <h2>Fórmula do Erlang B</h2>
                        <p>A fórmula do Erlang B para calcular a probabilidade de bloqueio, número de canais e tráfego é a
                            seguinte:</p>
                        <h3>Probabilidade de Bloqueio</h3>
                        <div class="formula">
                            <p>Probabilidade de Bloqueio = <sup>Tráfego<sup>Número de Canais</sup> / Número de Canais!</sup>
                                / Σ(k=0 até Número de Canais) <sup>Tráfego<sup>k</sup> / k!</sup></p>
                        </div>
                        <h3>Número de Canais</h3>
                        <div class="formula">
                            <p>Número de Canais = ln(Tráfego) - Σ(n=1 até Número de Canais) <sup>Tráfego<sup>n</sup></sup> /
                                n!</p>
                        </div>
                        <h3>Tráfego</h3>
                        <div class="formula">
                            <p>Tráfego = (Taxa de Chegada de Chamadas) * (Duração Média da Chamada)</p>
                        </div>
                    </div>
                    <div class="right">
                        <div class="formulario">
                           <h2>Cálculo da Probabilidade de Bloqueio</h2>
                        <div class="c">
                            <form action="" method="POST">
                             {%csrf_token%}
                             <label>trafego: <input type="number" name="t"></label>
                             <br>
                             <label>número de canais: <input type="number" name="c"></label>
                             <br>
                             <button type="submit" style="color: white;">Calcular</button>
                         </form> 
                         </div> 
                         <div class="resultado">
                            <p>{{resultado}}</p>
                        </div> 
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </body>

{% endblock main %}

templates/core/index.html
{% extends "layout.html" %}

{% block style %}
<style>
    article {
        color: white;
    }

    article .img {
        align-content: flex-end;
    }

    .esquerda {
        float: left;
        width: 50%;
        text-align: left;
        margin-top: 100px;
    }

    .direita {
        float: left;
        width: 50%;
        text-align: center;
    }
</style>

{% endblock style %}

{% block main %}
<div class="blocomain">
    <div class="esquerda">
        <article>
            <p>Este website congrega conteúdos desenvolvidos na UC de Complementos de Redes.</p>
            <p>Tais como o desenvolvimento de uma página Web em Django e html.</p>
            <p>Procura também ser um meio para guardar a informação transmitida em aula, tais como os temas abordados
                dos tópicos.</p>
        </article>
    </div>

    <div class="direita">
        <article>
            {% load static %}
            <img src="{% static 'core\redes.jpeg' %}" width="500px" alt="">
        </article>
    </div>
</div>



{% endblock main %}

</body>

</html>

templates/core/plan3.html
{% extends "layout.html" %}

{% block style %}
<style>
    h1 {
        width: 100%;
        padding: 15px;
        background: #f0f0f5;
        box-shadow: 0 0 100px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        display: flex;
        justify-content: center;
        align-items: center;
        color: #34495e;
    }

    h2 {
        text-align: left;
        color: white;
    }

    img {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 50px;
        margin-left: 200px;
    }
    .resultado {
        margin-top: 30px;
        margin-left: 100px;
        color: white;
    }

</style>

{% endblock style %}


{% block main %}

<body>
    <div>
        <h1>Planemaneto Celular</h1>
        <div>
            <h2>Gráfico com C/I relativo a vários padrões celulares</h2>
            <div class="resultado">
                {% load static %}
                <img src="{% static 'core/grafico6.png' %}" alt="">
            </div>
        </div>
    </div>
    <div>
        <h2>Heatmap de C/I para Padrões Celulares</h2>
        <div class="resultado">
            {% load static %}
            <img src="{% static 'core/grafico7.png' %}" alt="">
        </div>

</body>
{% endblock main %}