config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('core.urls'), name='core')
]

core/urls.py
from importlib.machinery import ExtensionFileLoader
from django.urls import path
from . import views


app_name = 'core'

urlpatterns = [
    path("", views.index_view, name='index'),
    path("aspetos/", views.aspetos_view, name='aspetos'),
    path("cenario/", views.cenario_view, name='cenario'),
    path("diagrama/", views.diagrama_view, name='diagrama'),
    path("planeamento/", views.planeamento_view, name='planeamento'),
    path("plan2/", views.plan2_view, name='plan2'),
    path("plan3/", views.plan3_view, name='plan3'),
    path("trafego/", views.trafego_view, name='trafego'),
    path("erlangB/", views.erlangB_view, name='erlangB'),
    path("canais/", views.canais_view, name='canais'),
    path("calctraf/", views.calctraf_view, name='calctraf'),
    path("topicos/", views.topicos_view, name='topicos'),
    path("Conversor/", views.conversor_view, name='conversor'),
    path("nyquist/", views.nyquist_view, name='nyquist'),
    path("shannon/", views.shannon_view, name='shannon'),
    path("meios/", views.meios_view, name='meios'),
    path("sinais/", views.sinais_view, name='sinais'),
    path("mpsk/", views.mpsk_view, name='mpsk'),
    path("mqam/", views.mqam_view, name='mqam'),
    path("modulacoes/", views.modulacoes_view, name='modulacoes'),
    path("edita_topicos", views.edita_topicos_view, name='edita_topicos'),
    path("novo_topico/", views.novo_topico_view, name='novo_topico'),
    path("edita_topico/<int:topico_id>", views.edita_topico_view, name='edita_topico'),
    path("apaga_topico/<int:topico_id>", views.apaga_topico_view, name='apaga_topico'),
    path("novo_conteudo/", views.novo_conteudo_view, name='novo_conteudo'),
    path("edita_conteudo/<int:conteudo_id>", views.edita_conteudo_view, name='edita_conteudo'),
    path("apaga_conteudo/<int:conteudo_id>", views.apaga_conteudo_view, name='apaga_conteudo'),
]

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CoRe</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🕸</text></svg>">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% block style %}

    {% endblock style %}

</head>

<body>
    <header>
        <div class="logo">
            {% load static %}
            <img src="{% static 'core\logo.png' %}" width="300px" alt="">
        </div>

        <div class="menu">
            <nav>
                <a href="{% url 'core:index' %}" class="btn">Home</a>
                <a href="{% url 'core:topicos' %}" class="btn">Topicos</a>
                <a href="{% url 'core:conversor' %}" class="btn">unidades logaritmicas</a>
                <div class="dropdown">
                    <button class="dropbtn">
                        limites fundamentais
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-content">
                        <a href="{% url 'core:nyquist' %}">Limite de Nyquist</a>
                        <a href="{% url 'core:shannon' %}">Capacidade de Shannon</a></a>
                    </div>
                </div>
                <a href="{% url 'core:meios' %}" class="btn">Meios de transmissão</a>
                <a href="{% url 'core:sinais' %}" class="btn">Sinais</a>
                <div class="dropdown">
                    <button class="dropbtn">
                        Modulações
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-content">
                        <a href="{% url 'core:modulacoes' %}">Teórica</a>
                        <a href="{% url 'core:mpsk' %}">M-PSK</a>
                        <a href="{% url 'core:mqam' %}">M-QAM</a></a>
                    </div>
                </div>
                <a href="{% url 'core:aspetos' %}" class="btn">Aspetos de propagação</a>
                <a href="{% url 'core:cenario' %}" class="btn">Campanha de medidas</a>
                <a href="{% url 'core:diagrama' %}" class="btn">Diagrama</a>
                <div class="dropdown">
                    <button class="dropbtn">
                        Planeamento Celular
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-content">
                        <a href="{% url 'core:planeamento' %}" class="btn">Cobertura-Frequencias</a>
                        <a href="{% url 'core:plan2' %}" class="btn">Cobertura-Atenuação</a>
                        <a href="{% url 'core:plan3' %}" class="btn">Planeamento Celular2</a>
                    </div>
                </div>
                <div class="dropdown">
                    <button class="dropbtn">
                        Tráfego
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-content">
                        <a href="{% url 'core:trafego' %}" class="btn">Teoria</a>
                        <a href="{% url 'core:erlangB' %}" class="btn">Erlang B - Prob. Bloqueio</a>
                        <a href="{% url 'core:canais' %}" class="btn">Canais</a>
                        <a href="{% url 'core:calctraf' %}" class="btn">Tráfego</a>
                    </div>
                </div>
            </nav>
        </div>

    </header>

    <main>
        {% block main %}

        {% endblock main %}
    </main>

    <footer style="color: white;">
        Universidade Lusófona @ 2022
    </footer>

</body>

</html>